version: '3.4'

services:
  dockerizedmvcnbg:
    image: ${DOCKER_REGISTRY-}dockerizedmvcnbg
    container_name: person.mvc
    build:
      context: .
      dockerfile: DockerizedMvcNbg/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081 

  person.database:
    image: postgres:alpine
    container_name: person.database
    ports:
      - "5432:5432"
    volumes:
      - ./.containers/products-db:/var/lib/postgresqldata
    environment:
      -  POSTGRES_DB=persons
      -  POSTGRES_USER=postgres
      -  POSTGRES_PASSWORD=postgres

  person.cache:
    image: redis:7.2.4-alpine
    container_name: person.cache
    restart: always
    ports:
      - '6379:6379'


